### ISSUE TITLE
Provide means for encrypting the password in dw.json

### ISSUE THREAD

**Issue by zlatinz** [SqrTT/prophet#102]
Currently the dw.json has the password for connection to the instance in plain text format. 
This could be a security issue, should someone gain access to the dw.json file.

**Comment by SGD1953** [comment]
Easer solution might be to allow omitting the password and if it is not provided you would have to type it on startup.

**Comment by SqrTT** [comment]
from `v1.0.9` `password` field in `dw.json` in optional and if omitted will be asked form user during the first connection to a sandbox.

Not sure how much it is secure since password still persists in memory unencrypted. IMHO encryption makes sense only if would be possible to pass encrypted password directly to SB (use `Digest` auth instead of `Basic`) so the extension would operate only password's hash instead on raw password...
