### ISSUE TITLE
Upload pop up for leave all, remove all etc... does not appear 

### ISSUE THREAD

**Issue by sdhal** [SqrTT/prophet#116]
Hi,

I am facing a weird behaviour,

1. hit command to clean upload in vscode
2. check output terminal for progress
3. progress halts and clean cartridges, expecting a pop up to action for leave all, remove all etc...
4. however i am unable to see this pop up when connected on laptop screen, hence cannot action and cannot proceed as well.
5. however when i connect to bigger screen this popup appears and i can interact and proceed.
6.Seems like position of popup is not correct when working with smaller screen in vs code.

Is there any setting i can use, or something ? 

Regards
Shailesh

**Comment by SqrTT** [comment]
Hi @sdhal 

Thanks for reporting.
The extension uses VSCode API to show popup and can't affect UI. Unfortunately currently to way to disable this popup. Probably I could add config for this but due to limited time not sure when I will be able to do that.
Probably VSCode team will fix the issue faster.

**Comment by SqrTT** [comment]
this is not the issue of extension but VSCode. Closing since nothing I can do here.
