### ISSUE TITLE
Disable htmlhing

### ISSUE THREAD

**Issue by mcclaskiem** [SqrTT/prophet#131]
Is there a way to disable `htmlhing` in the config of the extension? 

I have other ways of performing this task outside of the Prophet plug-in and currently my editor just shows an error on every template and every line as a result of the latest commit.

Thanks!

**Comment by SqrTT** [comment]
Hi, @mcclaskiem 
There is no possibility yet. Will be added in next release.

**Comment by mcclaskiem** [comment]
@SqrTT Awesome thanks so much! Would you happen to have an ETA?

**Comment by dlopezSoul** [comment]
Hello, we would really love the option to disable htmlHint as well, but maybe, while the next version is coming...
Is there a way to change the settings of the htmlhint?
We need this so bad because we get 1 error per line on every ISML file, telling us to use spaces instead of tabs, which fills our work environment of errors and red:
![image](https://user-images.githubusercontent.com/42540226/45700249-49928000-bb6c-11e8-960b-f8351016a606.png)
If at least we could select tabs as something 'correct' we wouldn't get that many errors.
If this is neither an option then we will eagerly wait for next release :)

Thank you so much.

**Comment by SqrTT** [comment]
Hi @mcclaskiem @dlopezSoul 

In version 1.0.18 htmlhint can be disabled by option `extension.prophet.htmlhint.enabled`, Also default configs may be changed from default  by `.htmlhintrc` file (more info https://github.com/htmlhint/HTMLHint/wiki/Rules).

Please confirm if it works for you.
