### ISSUE TITLE
<isscript> tag should not be used?

### ISSUE THREAD

**Issue by Jakobud** [SqrTT/prophet#223]
**Describe the bug**
Prophet's ISML language server reports that `<isscript>` tags should not be used. But I don't see this anywhere in the SFCC documentation.

**To Reproduce**
1. Create an `<isscript>` tag
2. Note that it will be highlighted as an issue in the UI

**Screenshots**
![Screen Shot 2020-03-04 at 8 24 05 AM](https://user-images.githubusercontent.com/87356/75894681-d0cfc400-5df1-11ea-8c43-b332850a8557.png)

Here is the URL that tooltip links to:
https://documentation.b2c.commercecloud.salesforce.com/DOC1/index.jsp?topic=%2Fcom.demandware.dochelp%2FISML%2Fisscript.html

**Comment by SqrTT** [comment]
Hi @Jakobud 
yes, usage of `isscript` is bad practice and should be avoided. Because increase amount of business logic in templates which is hard to support/maitinence.
SFRA don't use `isscript` (well, use only for inject assets but only because they didn't found workaround).

probably wording of warning message may be improved :)

**Comment by Jakobud** [comment]
Great thanks. Makes sense.
