### ISSUE TITLE
Option to turn off the const/let warning

### ISSUE THREAD

**Issue by strumwolf** [SqrTT/prophet#228]
**Is your feature request related to a problem? Please describe.**
`const` and `let` are being flagged, as intended by the extension. Since I am using `const` and `let` within the restrictions of Rhino, this is annoying to see my files lit up in red where const and let are utilized.

**Describe the solution you'd like**
An option in the settings to ignore the use of `const` and `let`. Default to true of course but it would be nice to be able to turn this diagnostic off.

**Describe alternatives you've considered**
Obviously going back and changing all the `const` and `let` instances too `var`. I've utilized `const` and `let` correctly in multiple places and would rather not have to go back and refactor.

**Additional context**

**Comment by fgiust** [comment]
+1 on this.

Validation added in version 3.1 is a problem for anybody using const/let (which are allowed in Rhino, although they have some nonstandard behavior they have some advantages with standard editors and linting).

JS linting is usually delegated to eslint for which there are several sfcc shared configurations (e.g. https://github.com/jenssimon/eslint-config-sfcc) and we don't need an additional, not configurable validation from prophet.
Please add a flag for enabling/disabling js linting.

**Comment by SqrTT** [comment]
thanks for taking time for issue.

Unfortunately, this is not too simple like it looks. Const/let warning is actually a side effect. Acorn (JS parser) is unable to parse let/const in ES5 mode and rises exception when face const/let. Acorn/parser is needed to introduce code assistance, autocomplete, goto features and some diagnostics. Currently it's have only one rule related to require custom script in global scope, but in future is planned to add more (eg. warning at deprecated methods usage). Yes, I know about eslint. ESlint is great tool, but it makes linting related to JS, while the extension make checks related to SFCC so they are not intersect. Of course those rules can be implemented as ESLint plugin, even more, similar plugins exists but why is using them (who knows about them), for instance [eslint-plugin-sitegenesis](https://www.npmjs.com/package/eslint-plugin-sitegenesis).

Regarding usage of let/const. Rhino really supports but they have non standard behavior (actually Rhino died before standard was approved). Personally I widely use let/const and know about advantages (may see in source code of extension). Unfortunately, things become worse when we taking about SFCC. I remember at least five times when bug fixing end up by change `const -> var` and no one in opposite way :). Also this is choice of SFCC guys, SFRA implemented without any const/let. So better would be follow SFRA way in this.

Regarding disabling diagnostics. I'll add this thing since is not hard so you will not see those boring warnings. But except diagnostics you may lost some additional features.

PS. I'll add option to disable once have time for it since pretty busy this time.

**Comment by SqrTT** [comment]
this can be disabled by `extension.prophet.script.server.disable.diagnostics` in v1.3.5

**Comment by SqrTT** [comment]
option implemented in v1.3.5
