### ISSUE TITLE
Publish the extension to the Open VSX Registry

### ISSUE THREAD

**Issue by schroeder-mobizcorp** [SqrTT/prophet#278]
**Is your feature request related to a problem? Please describe.**
We would like to be able to use the extension in IDE's other than Visual Studio Code.

**Describe the solution you'd like**
Please publish the extension on [Open VSX Registry](https://open-vsx.org) so we can use it in IDE's that are compatible with the Visual Studio Code Extension API, e.g. [Theia](https://theia-ide.org).

**Describe alternatives you've considered**
We could also download the .vsix from the Visual Studio Marketplace and install it manually. The problem here is that this is against the [Microsoft Visual Studio Marketplace Terms of Use](http://aka.ms/VSMarketplace-TOU):

> Marketplace Offerings are intended for use only with Visual Studio Products and Services and you may only install and use Marketplace Offerings with Visual Studio Products and Services.

**Comment by SqrTT** [comment]
Hi @schroeder-mobizcorp 
Thank you for an idea. I was not aware something like this exists. I'll take a look and see how to publish there.

But I see few potential problems. Major problem is lack of the time. Currently I myself can't cover all platforms where VSCode is working and with projects specifics settings. If I'll publish it to Open VSX Registry amount of platforms increases dramatically and I'll not able to catch reasonable amount of bugs and guaranty stability.

Another point. I'm not sure if there are enough of users that will use tool. For instance I'll spend +200% time for verification and in result there are 10 user which will actually use the tool.

Anyway I'll try to publish but without guaranty from my side. But to ETA for this...


PS. Not sure if Theia is applicable for SFCC. Because clients of SFCC is commercials with some level of security usually they don't like cloud solutions to host they code. Code can be stolen or even worse some bad code may be injected.

**Comment by schroeder-mobizcorp** [comment]
Hi @SqrTT,
here is a document which explains how you can publish the extension to Open VSX Registry: https://github.com/eclipse/openvsx/wiki/Publishing-Extensions.
It also has a link at the bottom for a GitHub action which can be used to automatically publish the extension to Open VSX Registry and the Visual Studio Marketplace.

That could also mitigate the time problem you are currently facing because it can also accelerate the publishing process to Visual Studio Marketplace which I assume you currently do manually.

Thanks for the hint regarding potential security implications of cloud solutions like Theia.

**Comment by SqrTT** [comment]
I've tried to publish but faced some weird error:
```
 DONE  Packaged: /tmp/tmp-1166321IzMaQdgKjF2a.vsix (379 files, 1.46MB)

❌  The server responded with status 413: Request Entity Too Large
See the documentation for more information:
https://github.com/eclipse/openvsx/wiki/Publishing-Extensions
```

I'll try to find out solution once have time.

**Comment by SqrTT** [comment]
seems that was temporary outage https://github.com/EclipseFdn/open-vsx.org/issues/432

The extension has been successfully published https://open-vsx.org/extension/SqrTT/prophet
