### ISSUE TITLE
Timeout Uploading Cartridges

### ISSUE THREAD

**Issue by BenKowalski** [SqrTT/prophet#280]
Hello @SqrTT,

I have problems uploading the cartridges with this error (IP hidden):

```
Error: Error: connect ETIMEDOUT 194.***.*.**:443
	at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1141:16)
```

This bug seems connected to #232 

**Steps to reproduce the behavior:**
Start vscode
2 prophet starts uploading
See error in output window and reload starts

**Expected behavior**
No timeout should occur.

**Desktop (please complete the following information):**
 - macOS Bis Sur v11.2.3
 - VSCode v1.54.3
 - Prophet Debugger v1.4.13

This happens when I'm connected to my new internet provider. Upload is around 16 Mbps. It might be a network issue but I don't get why. Upload should be sufficient and there's no package loss. I do not encounter any issues with any other service. Restarting the sandbox does not solve the issue.

Is there a possibility to set the timeout (15 seconds, if this is right?) to a longer period? This basically blocks me from working right now. 

Anyway, thanks for developing this extension! 👌🙂

**Comment by SqrTT** [comment]
Hi @BenKowalski 
Well this is painful issue. Since always hard to reproduce. And I've already did a lot of work to optimize upload... but as you see that's not enough... and I have no ideas where to move with this...

Your suggestion for 15 sec timeout already don't work since current timeout is 20 sec. 

see:
https://github.com/SqrTT/prophet/blob/master/src/server/WebDav.ts#L33-L39

Probably option is for you is uncheck 'Upload on start' this may save some time

![image](https://user-images.githubusercontent.com/1271300/112617913-3d1eca80-8e2e-11eb-998e-b62a536bc152.png)

PS. package loss may be visible only with large packages try
```
ping <sandboxDomain> -s 1500
```
But again this will show package loss only for ICMP protocol and there could different picture for TCP/HTTPS

**Comment by BenKowalski** [comment]
Thanks for the fast answer. The unchecking of "upload all on editor startup" did not work out. It's the same for single files. Then I tested your ping command and first, it gave me this 29 times:

`Request timeout for icmp_seq 0`

and afterwards

`556 bytes from 13.108.*.***: Frag reassembly time exceeded
Vr HL TOS  Len   ID Flg  off TTL Pro  cks      Src      Dst
 4  5  00 b405 49af   0 0000  36  01 8dc0 192.168.*.***  194.145.*.***`

So it means, that something is not correct, right?

**Comment by SqrTT** [comment]
yes, that's mean something is wrong with networking. Probably you may reach out provider's support with this.

**Comment by SqrTT** [comment]
I believe this can be closed. Feel free to reopen if still actual.

**Comment by gabrielfreiberg** [comment]
@SqrTT and all -- I was facing this issue and found that a Proxy application installed by my company's IT Group was causing it.

Adding this info to this issue, should it help anyone else in the future.

Thanks
