### ISSUE TITLE
No cartridge overview in explorer

### ISSUE THREAD

**Issue by michaelterryio** [SqrTT/prophet#284]
**Description**
I noticed on someone's [blog post](https://medium.com/@manusaini0088/visual-studio-code-integration-with-demandware-aka-salesforce-commerce-cloud-b2c2ff49e22b) that they have a cartridges section in their explorer pane. I assume that's what the readme means by "cartridges overview." I've installed Prophet and it's uploaded cartridges, but I don't have a logs or cartridges section in my explorer. I read your readme and scanned the settings but I don't see how to enable this.

**To Reproduce**
1. Open a project in explorer.

**Expected behavior**
I expected to see a cartridges section.

**Screenshots**
![image](https://user-images.githubusercontent.com/57774951/114101344-74ec3000-987a-11eb-81ea-6f75715dc4ad.png)

**Desktop (please complete the following information):**
 - OS: macOS Big Sur (11.2.2)
 - VSCode version: Version: 1.55.1
 - The extension version: v1.4.16

**Additional context**
I tried adding a list of cartridges in settings, but that didn't enable it either.

**Comment by SqrTT** [comment]
Hi @michaelterryio 
Well, you have find very complicated way to open cartridges and logs view... this is much simpler

![image](https://user-images.githubusercontent.com/1271300/114147769-b5eb4f80-9921-11eb-8501-7f24e3fdddd5.png)

**Comment by SqrTT** [comment]
seems author of article have moved logs/cartridges section via drag&drop to explorer tab.

**Comment by michaelterryio** [comment]
So that's how you do it!

Keep in mind, I didn't notice that on my own. Maybe a small note in the readme that such a thing even exists? An abstract icon in that control strip is reasonably discoverable, but not the *most* discoverable, as I found.

**Comment by bboydflo** [comment]
Hi, thanks for this extension. 

I am on big sur (version 11.2.3) and can not see cartridges either. I am inspecting cartridges subsection under prophet extension cloud icon. No matter what I do, prophet is unable to detect cartridges in my project. and when I do a clean/upload it finishes really quick since it is unable to detect cartridges. I have placed `dw.json` in my root folder as well as in other subfolder inside my project.

My current project has a build system in place that needs to run in node 10 (I am using nvm). can that conflict with prophet? (I think vscode still uses node12 internally). What is the way to debug why prophet does not detect any cartridges?

**Comment by SqrTT** [comment]
Hi @bboydflo 
Seems you have different issue then current one (current one is about absence cartridges subsection which present in your case).

Cartridge detection relay on `.project` files so please make sure `.project` exists for every cartridge and `.project` is not excluded form search.

The extension doesn't depend on node version installed in system since VSCode use 12 (your assumption is correct)

**Comment by bboydflo** [comment]
> Hi @bboydflo
> Seems you have different issue then current one (current one is about absence cartridges subsection which present in your case).
> 
> Cartridge detection relay on `.project` files so please make sure `.project` exists for every cartridge and `.project` is not excluded form search.
> 
> The extension doesn't depend on node version installed in system since VSCode use 12 (your assumption is correct)
> 
> ![image](https://user-images.githubusercontent.com/1271300/115373934-0477d400-a1d5-11eb-95f5-48aea328d834.png)

My issue was indeed related to `.project` files being excluded from search in vscode. It works now. Thanks a lot! <3
