### ISSUE TITLE
Prophet-ts errors on a JavaScript backend?

### ISSUE THREAD

**Issue by ValentinGurkov** [SqrTT/prophet#293]
Hello,

Since recent updates, I'm seeing prophet-ts errors triggered on the JavaScript backend files regarding various variable types.
For example:
`(local var) variable: string | number | boolean | Date | EnumValue<string | number> | string[] | number[] | MarkupText | null
Type '{}' is not assignable to type 'string | number | boolean | Date | EnumValue<string | number> | string[] | number[] | MarkupText | null'.
  Type '{}' is not assignable to type 'null'`

If using TypeScript this error should make sense but for JavaScript files, it should not be visible, right? Am I misunderstanding the purpose of this? I'm also not sure how to configure this without disabling the script diagnostics/linting in the settings completely. It doesn't seem to be tied to `jsconfig.json`.

Can somebody please help me out in understanding the purpose of this and how to make use of this correctly, or turn it off?

To clarify, I'm not sure whether this is a bug or an incorrect usage of the extension from my end.

Thanks.

**Comment by shr1k4nt** [comment]
I was going to create an issue for the same. Glad I'm not the only one getting this.
What I found was that if you disable diagnostics/script linting, this stops.(See below screenshot)

![Screenshot 2021-05-26 at 22 31 40](https://user-images.githubusercontent.com/4485699/119727175-48b06100-be72-11eb-95c6-9c9d4b2d7500.png)

**Comment by ValentinGurkov** [comment]
> I was going to create an issue for the same. Glad I'm not the only one getting this.
> What I found was that if you disable diagnostics/script linting, this stops.(See below screenshot)
> 
> ![Screenshot 2021-05-26 at 22 31 40](https://user-images.githubusercontent.com/4485699/119727175-48b06100-be72-11eb-95c6-9c9d4b2d7500.png)

That is one way of solving this, though I think this setting is responsible for more things and we're also switching them off

**Comment by SqrTT** [comment]
Hi @ValentinGurkov 
Thank you for reporting.
Yes, as you assumed correctly this warnings are cumming from TypeScript Server which is build it in the extension. It allows introduce better code assistance along with type checking. 

At this moment configuration in hardcoded, that's why `jsconfig.json` (along with other ways) doesn't work. I'll add option to configure this is the feature. But note there not way to disable warnings like in your initial comment.

So your options is:
* disable linting globally (and relay on different tool/plugin for linting like ESLint)
* disable linting on file level (options `@ts-check`, `@ts-ignore` and so one)
* provide correct types to make type checker happy (hint: you may use JSDoc comment to achieve this. See more here https://www.typescriptlang.org/docs/handbook/jsdoc-supported-types.html)

**Comment by ValentinGurkov** [comment]
Hi @SqrTT,
Thanks for providing a clear explanation of how this works and your future plans.  I also want to mention that I love the code assistance for ISML! I believe the options are pretty clear, we know what to do in this case, so I'll be closing my issue.

**Comment by zeeshan1001** [comment]
@SqrTT is this issue resolved? The problem I am facing is that all SiteGenesis code gets these kinds of errors. We have a policy not to touch SiteGenesis code. How can we fix this.

![image](https://user-images.githubusercontent.com/22167378/130500096-8dc10e1d-6697-446a-ac67-f0b9059f2c9f.png)
