### ISSUE TITLE
Allow to debug cartridges in other folders

### ISSUE THREAD

**Issue by sGambolati** [SqrTT/prophet#295]
**Is your feature request related to a problem? Please describe.**
I would like to have my cartridge in a different folder structure (i.e: under `node_modules`) and enable to debug files under those cartridges (which are recognized by Prophet's Cartridge List).

**Describe the solution you'd like**
I would like to be able to specify (in `dw.json` for example) in which folders I would like debugger to search cartridge code (improve [this logic](https://github.com/SqrTT/prophet/blob/c635ad5ae3858a703461596930786c9d17977f69/src/mockDebug.ts#L734-L740))

**Describe alternatives you've considered**
Fork the project and fix it on my own.

**Additional context**

**Comment by SqrTT** [comment]
Hi @sGambolati 
Thank you for suggestion.

The extension doesn't search in for cartridges in `node_modules` by default because `node_modules` is like "black hole" it contains too much files and lookup for `.project` in this folder took to much time (in my case `node_modules` is around 1Gb)

SFCC ecosystem never relays on node_modules hence I see no much reason to scan this folders for cartridges

anyway this way currently is hardcoded [here](https://github.com/SqrTT/prophet/blob/c635ad5ae3858a703461596930786c9d17977f69/src/lib/FileHelper.ts#L110) and is not configurable

**Comment by sGambolati** [comment]
Hi @SqrTT . 

Thanks for your reply.

We finally solved this issue using [SymLinks](https://linuxize.com/post/how-to-create-symbolic-links-in-linux-using-the-ln-command/). With this we are able to _cheat_ debugger really simple, using `preLaunchTask` and `postLaunchTask` in launch.json in **VS Code**.

SG!

**Comment by SqrTT** [comment]
yeah, I've thought to suggest symlinks but was not sure how well they work on windows

**Comment by sGambolati** [comment]
Actually, we created a Windows and Linux VS Code Config. Not the most elegant solution, but it works!
