### ISSUE TITLE
Intellisense not triggered

### ISSUE THREAD

**Issue by Hijdra** [SqrTT/prophet#310]
**Describe the bug**
When starting a separate link / plugin cartridge in a repository Javascript / Typescript Intellisense does not work. 
In the example below I'm using public repositories that all are not mine but want to create a similar setup as 'link_nexipayments'.

I've been looking in code source of extension and trying to figure out what triggers node script language server but am at a dead end after looking for hours into the issue.

**To Reproduce**
1. Create test folder
2. Clone https://github.com/SalesforceCommerceCloud/link_nexipayments.git 
3. Clone https://github.com/SalesforceCommerceCloud/storefront-reference-architecture.git
4. Clone https://github.com/SalesforceCommerceCloud/dw-api-types.git
5. Add dw.json in link_nexipayments/cartridges/
6. Open link_nexipayments in vscode
7. Open file: cartridges/int_nexixpay/cartridge/scripts/helpers/paymentInstrumentHelper.js
8. Hit F12 on Money of `const Money = require('dw/value/Money');`
9. Error: No definition found for 'Money'

**Expected behavior**
At step 9 I would expect to navigate to the Money.d.ts which works at my integration project including: SFRA + plugins + customizations.

**Screenshots**

No definition found for 'Money':
![image](https://user-images.githubusercontent.com/7012180/152825373-95d4b90d-9480-4890-a4dc-bd7efc2bc042.png)

I'm suspecting it happens because of the missing 'Script Language Server':
![image](https://user-images.githubusercontent.com/7012180/152820610-fade1cce-0481-4a61-a481-cc94a192623d.png)

Integration project containing many customizations:
![image](https://user-images.githubusercontent.com/7012180/152825656-97c42df0-0d2f-4862-aa29-feccb0f63243.png)

**Desktop (please complete the following information):**
 - OS: Windows 10
 - VSCode version: 1.63.2
 - The extension version: v1.4.25

**Comment by SqrTT** [comment]
Hi @Hijdra thanks for reporting

Seems in your case the extension unable figure out cartridges path, you may try out setup it manually via dw.js (`cartridgesPath` property)

```json
{
    "username": "<ddd>",
    "password": "<aaa>",
    "cartridgesPath": "link_nexipayments:app_storefront_base"
}
```
Potentially you may see error message regarding missing `cartridgesPath`

![image](https://user-images.githubusercontent.com/1271300/152836378-75537b84-7815-4dd3-93e3-ce574149a39c.png)

Hope it helps.

PS. In regular project you may don't need `cartridgesPath` since extension parses `site.xml` in order to get cartridges path
PPS. you don't need dw-api-types in your folders (https://github.com/SalesforceCommerceCloud/dw-api-types.git)
the extension comes with build in definitions

**Comment by Hijdra** [comment]
@SqrTT that did the trick! Thanks the quick help, confirming dw-api-types is duplicate and maintaining the extension for many years.
