### ISSUE TITLE
Error: webdav timeout Trying to re-upload cartridge

### ISSUE THREAD

**Issue by nakul280793** [SqrTT/prophet#323]
While uploading a code getting below error.

VSCode Node version: v16.13.0
Uploader disabled via configuration
Starting...
Using config file 'd:\SFRA_Code\dw.json'
dw.json hostname: 'xxxxxxxx.dx.commercecloud.salesforce.com'
dw.json version: 'SFRA_NewVersion'
Connection validated successfully
Current active version is: 'SFRA_NewVersion'
Start uploading cartridges
Cleanup code version...
[app_storefront_base] Deleting remote zip (if any)
[app_storefront_base] Zipping
[modules] Deleting remote zip (if any)
[modules] Zipping
[bm_app_storefront_base] Deleting remote zip (if any)
[bm_app_storefront_base] Zipping
[bm_app_storefront_base] Sending zip to remote
[app_storefront_base] Sending zip to remote
[modules] Sending zip to remote
[bm_app_storefront_base] Remove remote cartridge before extract
[modules] Remove remote cartridge before extract
[bm_app_storefront_base] Unzipping remote zip
[modules] Unzipping remote zip
[bm_app_storefront_base] Deleting remote zip...
[modules] Deleting remote zip...
**Error: webdav timeout
Trying to re-upload cartridge**
[app_storefront_base] Deleting remote zip (if any)
[app_storefront_base] Zipping
[app_storefront_base] Sending zip to remote
[app_storefront_base] Remove remote cartridge before extract
[app_storefront_base] Unzipping remote zip
[app_storefront_base] Deleting remote zip...
Cartridges uploaded successfully
Upload time: 3 min 14 sec
Watching files

**Comment by SqrTT** [comment]
uploading successfully finishes. app_storefront_base had timeout hence was re-uploaded from scratch. Jugging on upload time and cartridges amount (3) there are room for improving network quality. 
Not sure what else I may do here.

PS. double check size of **app_storefront_base**. For instance if it contains **node_modules** it may be huge (up to several giga bytes)

**Comment by mciudoiu** [comment]
@SqrTT me and my colleagues also run into this more and more often.
It happens for us for both SFRA and SG code bases, and it's usually the cartridge which contains the compiled static files which fails to be uploaded. It is indeed due to the size of it, but is not that large, they don't include any `node_modules` folders or stuff like that. It's usually the `.map` files which causes it be too large, and simply removing them fixes it temporarily.

Looking into `prohpet`'s source code I noticed that for any WebDAV request you allow [20 seconds](https://github.com/SqrTT/prophet/blob/78c5ea51b5e60936f73bcf3be3f9185dc81090cf/src/server/WebDav.ts#L38) for a request to complete. Is this timeout arbitrary or is it enforced by SFCC?
If this is not enforced it would be nice if it could be increased to 30 seconds, or something like that, and even better if you could make it into a preference so we can adjusted as necessary, should that be the case.

Thanks.

**Comment by SqrTT** [comment]
Hi @mciudoiu 
I've released version 1.4.30 with increased timeout to 40 second and with availability to change it via `dw.json`

Would you provide feedback for this version, please?

**Comment by mciudoiu** [comment]
Hi @SqrTT,
I can confirm that upload now works without timeouts with `40000`ms, and double checked again with `20000`ms and it does fail. So increasing the timeout fixes it.

Thank you again for the fast response update 👍

**Comment by pedrocapgemini** [comment]
@SqrTT How do I configure the dw.json file to increase the timeouts ?

**Comment by SqrTT** [comment]
@pedrocapgemini Have you tried `timeout` property in `dw.json`? (please note: you should have installed 1.4.30 version or above) 

PS. If 40 second is not enough for your sandbox most likely the issue is not with timeout.

**Comment by raphaeltorsu** [comment]
@SqrTT What might be the issue? Because I increased the timeout and have not made any significant changes to the codebase but I keep receiving the same error.

**Comment by dondenny5** [comment]
Is there a solution for this issue?

**Comment by SqrTT** [comment]
solution is reduce size of cartridge (make sure no `node_modules` are uploaded) or increase timeout.
