### ISSUE TITLE
Debugger not starting

### ISSUE THREAD

**Issue by RumenKaraivanov** [SqrTT/prophet#357]
Debugger was working fine and since yesterday all the sudden when i click "Attach to Sandbox" to start the debugger its 'thinking' for couple of seconds and its not starting, there is an error in the log files **Could not log in user** .I'm able to upload to my sandbox with no issue. I've tripple cheched my credentials and its all correct, changed my sandbox password, reinstalled vscode, made new workspace, tried with older versions of Prophet, checked **Enable Sandbox File System workspace** and removed it from the workspace which was mentioned in previous issues, still no success.
OS: Windows 10 Enterprise Version 22H2
VSCode version: 1.78.2
The extension version v1.4.40

**Comment by SqrTT** [comment]
Hi @RumenKaraivanov 
There were no update either of extension yesterday. Probably update of SFCC sandboxes. 
Please note similar issue happen with email. Since email is case sensitive for debugger but not sensitive for upload.
Also please try to use access key instead of password details here https://github.com/SqrTT/prophet/issues/279#issuecomment-807970171.

for reference: https://github.com/SqrTT/prophet/issues/313
https://github.com/SqrTT/prophet/issues/239#issuecomment-644512665

**Comment by RumenKaraivanov** [comment]
Issue fixed, thank you very much!
