### ISSUE TITLE
F12/go-to-definition stops working 

### ISSUE THREAD

**Issue by moorena** [SqrTT/prophet#360]
Installing 1.4.40 (also tested 1.4.38), the F12/go to definition command in VSC no longer works (gives the VSC "no definition found" hover/popup error). Downgrading to 1.4.31 fixes the problem.

**Comment by SqrTT** [comment]
Hi @moorena 
Latest versions of extension in order to work intelisense requires to be specified cartridges path. There are two ways via `dw.json`  `cartridgesPath` or add your project metadata (which contain `site.xml`) to workspace as folder and select current  site you are working on via `SFCC Context` menu (bottom right corner)

**Comment by moorena** [comment]
Got it. I will re-check. We maintain cartridge path in `site.xml`  (`custom-cartridges`). We use b2c tools for upload/maintaining, so `site.xml` is under a slightly different directory structure.
