### ISSUE TITLE
Why separated config file for upload and debug?

### ISSUE THREAD

**Issue by XEngine** [SqrTT/prophet#63]
First installation and I wonder if there is any logic behind separating the configuration files for uploading and debugging. 

I understand that while debugging vscode uses the launch.json. Can webdav uploader also use that same configuration?

Also, I see that webdav uploader if cartridges not defined, uploads everything. Since we can auto define all cartridge roots, can't we get changed file's cartridge root and upload by using it?

I would love to contrubite for this if these make sense.

**Comment by SqrTT** [comment]
Hi @XEngine
 The reason is historical. From the beginning, the extension has the only debugger and no uploader. By some time uploader was added with its own config file which is compatible with `uploader` (for easier migration)

I agree to have two config files it redundant, but this is minor issue to me, for example, more important thing is to prepare extension for [multi-root mode](https://code.visualstudio.com/updates/v1_17#_preview-multi-root-workspaces) (where each "root" can have its own config) and switch to use SDAPI 2.

>I would love to contrubite for this if these make sense.

Contribution always make sense :)

**Comment by XEngine** [comment]
Hi @SqrTT 

Thanks for the answer :)
Here is what I thought I can do as a feature for Prophet.

- Add sitegenesis cartridges with click like UX Studio
- A clean WebDAV support and version management (statusbar)
- Automated cartridge identifying:  Maybe create a hidden folder with symlinks for all cartridges to keep 'em tracking by file watchers 
- Custom icons for cartridge roots.
- Pipeline previewer. (Probably can't unless I manage to run react or vue inside vscode. Even if I can I may not be able to do 😃 )

I see no roadmaps and want to make something that almost makes no need for eclipse shit. so I think I can freely contribute since we are not a huge community over other languages :)
