### ISSUE TITLE
Setting the "cartridgeroot" in launch.json does not change the cartridge root

### ISSUE THREAD

**Issue by yhuang814** [SqrTT/prophet#79]
Hello all,

Thank you for creating this amazing tool! I am experiencing issues with the cartridges uploaded to the incorrect path in Webdav. 

Cartridge root path in my local project:
[project_folder]/cartridges
[project_folder]/cartridges/store_controllers
[project_folder]/cartridges/store_core

launch.json in .vscode/launch.json file

```
{
    "version": "0.3.0",
    "configurations": [
        {
            "type": "prophet",
            "request": "launch",
            "name": "Dev15 Sandbox",
            "hostname": "<hostname>",
            "username": "<username>",
            "password": "<password>",
            "codeversion": "version1",
            "cartridgeroot": "/Applications/XAMPP/xamppfiles/htdocs/<project_name>/cartridges",
            "workspaceroot": "${workspaceRoot}"
        }
    ]
}
```

As you can see above, the cartridge root path is defined in <project_name>/cartridges. However, when I use the watch file functionality to automatically update changes to webdav, it uploads to the incorrect path.

Current State - Incorrect Cartridge path on webdav: 
Cartridges/version1/cartridges/store_controllers
Cartridges/version1/cartridges/store_core

Desired Correct Cartridge Path on webdav:
Cartridges/version1/store_controllers
Cartridges/version1/store_core

Your help will be greatly appreciated!

Thanks

**Comment by SqrTT** [comment]
Hi @yhuang814 

Basically, there are two configurations (I know this is odd but happened historically):
* `launch.json` used by a debugger
* `dw.json` used for uploading

You are not provided `dw.json` but it exists since something is uploaded.
If the file is placed `/Applications/XAMPP/xamppfiles/htdocs/<project_name>/dw.json` then configuration should be like next
```
{
    "hostname": "<host>.demandware.net",
    "username": "<username>",
    "password": "<password>",
    "code-version": "version1",
    "root": "cartridges"
}
```
> most likely property `root` is missing in your file.

Hope this helps.

PS. in your `launch.json` is set specific `cartridgeroot` I would suggest to set it to`auto`

**Comment by SqrTT** [comment]
feel free to reopen in case issue isn't fixed
