### ISSUE TITLE
Add support for "~" in require path

### ISSUE THREAD

**Issue by dmersiowsky** [SqrTT/prophet#80]
As of today, code completion and type hinting is not working if a tilde is part of the require path.

Example: 

```
// Not working
var guard = require('~/cartridge/scripts/guard');

// Working
var guard = require('app_storefront_core/cartridge/scripts/guard');
```

Expectation would be that "~" is resolved properly.

**Comment by SqrTT** [comment]
Hi @dmersiowsky 

Code assistance is based on TypeScript Server which supports the only CommonJS (ES7 modules import ) standard. Since `~`, `*`, `superModule` is SFCC feature TypeScript doesn't support it. I'm not able to add it since it requires a lot of time which I don't have :(

Basically, TypeScript Server would require matching path resolving same as in SFCC (with knowledge about cartridges and its order). Things become more complicated in case multiple repositories with cartridges are used

**Comment by dmersiowsky** [comment]
Thanks for the prompt response. I suggest we leave it open for now, I might be able have a look at it myself some day.

**Comment by zlatinz** [comment]
I would suggest that this functionality uses "cartridge" configuration from dw.json in place of a cartridge path (it would be inaccurate, but it may help in the more simple scenarios).

**Comment by maxime121294** [comment]
Hi @dmersiowsky, 

You can use the [require cartridge resolve](https://marketplace.visualstudio.com/items?itemName=pikamachu.require-cartridge-resolve) extension for support of the following statements definitions:
- require('*/cartridge/...')
- require('~/cartridge/...') (sitegenesis)
- require('base/...')
- require('dw/...') (using "dw-api-types" repository definitions)
- module.superModule

@SqrTT, maybe we could integrate these functionnalities directly to Prophet extension ?

**Comment by SqrTT** [comment]
the extension doesn't do code assist. Code assistance is provided by TypeScript Server which is build in in VSCode. Unfortunately, I didn't find way how to affect path resolving in TypeScript Server.

**Comment by maxime121294** [comment]
It's not a very intelligent code assistant because it allows to use every method, even if they are not exported. Because of that, some methods sometimes are duplicated (the declaration and the export). However, it's still good to use :)

Here are some screenshots (with and without extension) : 

![without_extension](https://user-images.githubusercontent.com/10925177/56577719-00a41d80-65cc-11e9-96b3-9a62d728e06e.png)
![with_extension](https://user-images.githubusercontent.com/10925177/56577720-00a41d80-65cc-11e9-89c9-9405d6503879.png)

**Comment by SqrTT** [comment]
Latest versions (v1.2.27) has feature autocomplete file path for require and allows goto file via ctrl+click, 
But no code assistance so far.

**Comment by SqrTT** [comment]
version 1.4.0 comes with build in version of TypeScript. Which provide code assistance. TyoeScript version is modified to resolve SFCC way file resolving (handles correctly `*` and `~`).

Please note: dw.json should have property `cartridgesPath` to handle cartridges order correctly

**Comment by SqrTT** [comment]
closing since support were added
