### ISSUE TITLE
Multiroot wiki

### ISSUE THREAD

**Issue by shr1k4nt14** [SqrTT/prophet#94]
Please provide an example of uploading cartridges/debugging with a multi-root workspace.

**Comment by SqrTT** [comment]
Hi @shr1k4nt14 

Not sure what example is needed... Since `v1.0.0` autodetects cartridges. Just to start working with multiroot you need to add several folders containing cartridges. To ref a sandbox `dw.josn` still is required. It should present at least in one workspace.
 Also, no credential is required for a debugger. It reads config from `dw.josn`.

Or it doesn't work for you?

**Comment by shr1k4nt14** [comment]
You are right! The `dw.json` file was present in one workspace but it was missing the reference to the cartridge from another folder. Now I am able to debug the cartridge from another folder and the changes are being uploaded as well!

Thanks a lot!
